#define TXT_LOGIN1 0
#define TXT_PW1 1
#define TXT_LOGIN2 2
#define TXT_PW2 3
#define TRAY_ICON 4
#define APPWM_ICONNNOTIFY 5
#define APP_HIDE 6
#define APP_SHOW 7
#define APP_EXIT 8
#define BTN_Login1 9
#define BTN_Login2 10
#define BTN_AutoFree 11
#define BACKGROUND_BMP 12
#define STATIC_L1 13
#define STATIC_L2 14
#define STATIC_L 15
#define STATIC_PW 16
#define BTN_DONATION 17
#define BTN_DONATE_BMP 18

